import { QTableColumn } from "quasar";
export const salesReportColumns: QTableColumn[] = [
  {
    name: "date",
    label: "Date",
    field: "date",
    align: "left",
    sortable: true,
  },
  {
    name: "invoice_no",
    label: "Invoice No",
    field: "invoice_no",
    align: "left",
    sortable: true,
  },
  {
    name: "store_name",
    label: "Store Name",
    field: "store_name",
    align: "left",
    sortable: true,
  },
  {
    name: "customer_name",
    label: "Customer Name",
    field: "customer_name",
    align: "left",
    sortable: true,
  },
  {
    name: "product_name",
    label: "Product Name",
    field: "product_name",
    align: "left",
    sortable: true,
  },
  {
    name: "quantity",
    label: "Qty",
    field: "quantity",
    align: "right",
    sortable: true,
  },
  {
    name: "unit_price",
    label: "Unit Price",
    field: "unit_price",
    align: "right",
    sortable: true,
    format: (val: number) => `₱${val.toLocaleString()}`,
  },
  {
    name: "total_amount",
    label: "Total",
    field: "total_amount",
    align: "right",
    sortable: true,
    format: (val: number) => `₱${val.toLocaleString()}`,
  },
  {
    name: "payment_method",
    label: "Payment Method",
    field: "payment_method",
    align: "left",
    sortable: true,
  },
  {
    name: "status",
    label: "Status",
    field: "status",
    align: "left",
    sortable: true,
  },
  {
    name: "sales_rep",
    label: "Sales Rep",
    field: "sales_rep",
    align: "left",
    sortable: true,
  },
];
